Rvv v1.0 spmv
RALC88/riscv-vectorized-benchmark-suite pull request #30
Opened 2024-10-25 20:50 UTC by neiel-leyva

SPMV vectorized version.

2024-10-25 21:58 UTC, RALC88 commented on _spmv/src/spmv.c
> +    size_t   gvl    = __riscv_vsetvlmax_e64m1();
reemplazar todas las intrinsecas con su definición en vector_defines.h
por ejemplo : _MMR_VSETVLMAX_E64M1

2024-10-25 21:59 UTC, RALC88 commented on _spmv/src/spmv.c
> +            _MMR_u64 v_idx_row = __riscv_vle64_v_u64m1(&ja[idx+colid], gvl);
reemplazar todas las intrinsecas con su definición en vector_defines.h
Si alguna no esta definida en ese archivo, agregarla.

2024-10-25 22:04 UTC, RALC88 requested changes
Aparte de utilizar las definiciones mencionadas, el programa no verifica que el resultado es correcto. Podriamos agregar en el input file el resultado  y hacer una función para verificar el resultado ? Otra opción es imprimir el resultado en un archivo de salida. La primera quizá seria la mejor opción.

2024-10-29 18:27 UTC, neiel-leyva commented
> Aparte de utilizar las definiciones mencionadas, el programa no verifica que el resultado es correcto. Podriamos agregar en el input file el resultado y hacer una función para verificar el resultado ? Otra opción es imprimir el resultado en un archivo de salida. La primera quizá seria la mejor opción.

done!

2024-10-31 23:12 UTC, RALC88 approved these changes
LGTM

2024-11-04 13:51 UTC, merged